### ISSUE TITLE
Sphere objects

### ISSUE THREAD

**Issue by QGarchery** [QGarchery/broengine#4]
Complete the `sphere.go` file to implement the `Surface` interface.

**Comment by QGarchery** [comment]
![image](https://user-images.githubusercontent.com/22668539/123009329-c6f21b80-d3bc-11eb-9db2-a8908ceb2ed4.png)
There are some points on the sphere that are not rendered. Note that the shadow is full, so the intersection seems to be working.

**Comment by QGarchery** [comment]
![image](https://user-images.githubusercontent.com/22668539/123067622-6e993900-d411-11eb-8e21-f75847fe192c.png)

**Comment by QGarchery** [comment]
Specular looks better with high `a` value.

When inside a big sphere (notice the slight gradient in the background):
![image](https://user-images.githubusercontent.com/22668539/123075554-9dff7400-d418-11eb-9e6f-446d9006db0e.png)

**Comment by mlgarchery** [comment]
So pretty !
