### ISSUE TITLE
Parallelize pixel computations

### ISSUE THREAD

**Issue by mlgarchery** [QGarchery/broengine#6]
Read: https://spiralscout.com/blog/understanding-concurrency-and-parallelism-in-golang
In the future, we might need to speed up the rendering process by parallelizeing the task of computing a pixel color.

**Comment by QGarchery** [comment]
> Read: https://spiralscout.com/blog/understanding-concurrency-and-parallelism-in-golang

I could not follow this article, some code was missing.

I found this to be a better read:
https://hub.packtpub.com/concurrency-and-parallelism-in-golang-tutorial/
